### ISSUE TITLE
Error: Cannot find module 'run-sequence'

### ISSUE THREAD

**Issue by mkal1375** [iliakan/javascript-tutorial-server#11]
module.js:471
    throw err;
    ^

Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mkal/Documents/projects/jsinfo/js/javascript-tutorial-server/gulpfile.js:11:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by iliakan** [comment]
Did you `npm install` properly? The module is in `package.json`.
