### ISSUE TITLE
Gulp error occurs when trying to start server

### ISSUE THREAD

**Issue by urohit011** [iliakan/javascript-tutorial-server#21]
Hello @iliakan, when I run the command `./edit en` I get the following output on the console:

```
[07:26:10] Using gulpfile ~/Documents/Github/js/javascript-tutorial-server/gulpfile.js
[07:26:10] Starting 'webpack'...
[07:26:12] Starting 'jsengine:koa:tutorial:importWatch'...
[07:26:12] 'jsengine:koa:tutorial:importWatch' errored after 203 ms
[07:26:12] Error: Cannot find module 'getChromeLocation'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/urohit011/Documents/Github/js/javascript-tutorial-server/modules/jsengine/koa/tutorial/lib/getPlunkerToken.js:6:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/urohit011/Documents/Github/js/javascript-tutorial-server/modules/jsengine/koa/tutorial/lib/tutorialImporter.js:16:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/urohit011/Documents/Github/js/javascript-tutorial-server/modules/jsengine/koa/tutorial/tasks/importWatch.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
Gulp error details [ 'Cannot find module \'getChromeLocation\'',
  'Error: Cannot find module \'getChromeLocation\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:506:25)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/urohit011/Documents/Github/js/javascript-tutorial-server/modules/jsengine/koa/tutorial/lib/getPlunkerToken.js:6:27)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/urohit011/Documents/Github/js/javascript-tutorial-server/modules/jsengine/koa/tutorial/lib/tutorialImporter.js:16:25)\n    at Module._compile(internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\nat Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/urohit011/Documents/Github/js/javascript-tutorial-server/modules/jsengine/koa/tutorial/tasks/importWatch.js:3:24)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)' ]
(node:19008) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[webpack] Time: 5508ms
Built at: 10/22/2018 7:26:17 AM
                                          Asset       Size  Chunks             Chunk Names
../img/favicon/apple-touch-icon-precomposed.png   5.86 KiB          [emitted]
                     ../img/favicon/favicon.ico    5.3 KiB          [emitted]
                     ../img/favicon/favicon.png   1.29 KiB          [emitted]
                    ../img/favicon/tileicon.png   4.82 KiB          [emitted]
                             ../libs/animate.js  469 bytes          [emitted]
                        ../libs/class-extend.js   3.95 KiB          [emitted]
             ../libs/compareDocumentPosition.js  970 bytes          [emitted]
                                  ../libs/d3.js    143 KiB          [emitted]
                      ../libs/documentScroll.js   1.15 KiB          [emitted]
                            ../libs/domtree.css  313 bytes          [emitted]
                             ../libs/domtree.js   5.59 KiB          [emitted]
                         ../libs/event-mixin.js   1.25 KiB          [emitted]
                           ../libs/getCoords.js  819 bytes          [emitted]
                              ../libs/lodash.js    458 KiB          [emitted]
                                      footer.js   4.59 KiB       0  [emitted]  footer
                                  frontpage.css   2.49 KiB       1  [emitted]  frontpage
                                   frontpage.js   1.13 KiB       1  [emitted]  frontpage
                                        head.js   19.1 KiB       2  [emitted]  head
           modules/styles/blocks/font/icons.otf   22.6 KiB          [emitted]
          modules/styles/blocks/font/icons.woff   14.6 KiB          [emitted]
    modules/styles/blocks/page-footer/slack.svg   1.49 KiB          [emitted]
                                     styles.css   82.4 KiB       3  [emitted]  styles
                                      styles.js   1.13 KiB       3  [emitted]  styles
                                    tutorial.js   36.4 KiB       4  [emitted]  tutorial
Entrypoint head = head.js
Entrypoint footer = footer.js
Entrypoint tutorial = tutorial.js
Entrypoint styles = styles.css styles.js
Entrypoint frontpage = frontpage.css frontpage.js
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--7-1!node_modules/postcss-loader/src/index.js??ref--7-2!modules/jsengine/webpack/hover-loader.js!node_modules/stylus-loader/index.js??ref--7-4!tmp/en/frontpage.styl:
    Entrypoint mini-css-extract-plugin = *
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--7-1!node_modules/postcss-loader/src/index.js??ref--7-2!modules/jsengine/webpack/hover-loader.js!node_modules/stylus-loader/index.js??ref--7-4!tmp/en/styles.styl:
    Entrypoint mini-css-extract-plugin = *
[07:26:17] Finished 'webpack' after 7.44 s

```
I have node v10.12.0, npm v6.4.1 and gulp 3.9.1. Please help me figure it out.

**Comment by iliakan** [comment]
Please git pull the recent jsengine.

**Comment by urohit011** [comment]
It worked, thank you very much.

**Comment by urohit011** [comment]
The server starts and the home page shows all well, but there is this wrinkle though, all the chapter links are showing server error 500.

**Comment by iliakan** [comment]
pull and try now?

**Comment by urohit011** [comment]
Thanks for your response @iliakan, I will try it first thing tomorrow morning.

**Comment by urohit011** [comment]
It works all right now, thank you.
