### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by tankztc** [iliakan/javascript-tutorial-server#6]
I step-by-step walked through the installation guide, but it doesn't work. Can you kindly help me figure out what I'm missing? Thanks!!

(node:5834) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[01:00:23] Using gulpfile /js/javascript-tutorial-server/gulpfile.js
[01:00:23] Starting 'dev'...
[01:00:23] Starting 'client:sync-resources'...
[01:00:23] Finished 'client:sync-resources' after 54 ms
[01:00:23] Starting 'nodemon'...
[01:00:23] Starting 'client:livereload'...
[01:00:23] Starting 'client:webpack'...
[01:00:23] Starting 'watch'...
[01:00:24] livereload: listen on change public/pack/**/*.*,!public/pack/styles.js,!public/pack/head.js
[01:00:24] Using gulpfile /js/javascript-tutorial-server/gulpfile.js
(node:5835) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[01:00:24] Starting 'worker:nodemon'...
[01:00:25] [nodemon] 1.11.0
[01:00:25] [nodemon] to restart at any time, enter `rs`
[01:00:25] [nodemon] watching: /js/javascript-tutorial-server/handlers/**/* /js/javascript-tutorial-server/modules/**/*
[01:00:25] [nodemon] starting `node ./bin/server.js`
[01:00:25] Using gulpfile /js/javascript-tutorial-server/gulpfile.js
(node:5836) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
[01:00:25] Starting 'worker:client:webpack'...
[01:00:25] 'worker:client:webpack' errored after 83 ms
[01:00:25] Error: ENOENT: no such file or directory, open '/js/javascript-tutorial-server/tmp/styles.styl'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at Compiler.<anonymous> (/js/javascript-tutorial-server/modules/config/webpack.js:193:12)
    at Compiler.apply (/js/javascript-tutorial-server/node_modules/tapable/lib/Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (/js/javascript-tutorial-server/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/js/javascript-tutorial-server/node_modules/webpack/lib/webpack.js:22:48)
    at /js/javascript-tutorial-server/tasks/webpack.js:11:5
    at Gulp.<anonymous> (/js/javascript-tutorial-server/gulpfile.js:33:12)
    at module.exports (/js/javascript-tutorial-server/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:134:8)
    at /js/javascript-tutorial-server/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Gulp error details [ 'ENOENT: no such file or directory, open \'/js/javascript-tutorial-server/tmp/styles.styl\'',
  'Error: ENOENT: no such file or directory, open \'/js/javascript-tutorial-server/tmp/styles.styl\'\n    at Error (native)\n    at Object.fs.openSync (fs.js:641:18)\n    at Object.fs.writeFileSync (fs.js:1347:33)\n    at Compiler.<anonymous> (/js/javascript-tutorial-server/modules/config/webpack.js:193:12)\n    at Compiler.apply (/js/javascript-tutorial-server/node_modules/tapable/lib/Tapable.js:164:16)\n    at OptionsApply.WebpackOptionsApply.process (/js/javascript-tutorial-server/node_modules/webpack/lib/WebpackOptionsApply.js:62:18)\n    at webpack (/js/javascript-tutorial-server/node_modules/webpack/lib/webpack.js:22:48)\n    at /js/javascript-tutorial-server/tasks/webpack.js:11:5\n    at Gulp.<anonymous> (/js/javascript-tutorial-server/gulpfile.js:33:12)\n    at module.exports (/js/javascript-tutorial-server/node_modules/orchestrator/lib/runTask.js:34:7)\n    at Gulp.Orchestrator._runTask (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:273:3)\n    at Gulp.Orchestrator._runStep (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:214:10)\n    at Gulp.Orchestrator.start (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:134:8)\n    at /js/javascript-tutorial-server/node_modules/gulp/bin/gulp.js:129:20\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)' ]
[01:00:25] 'client:webpack' errored after 1.56 s
[01:00:25] Error in plugin 'll'
Message:
    Task ll:client:webpack failed
[01:00:25] 'dev' errored after 1.9 s
[01:00:25] Error in plugin 'run-sequence(client:webpack)'
Error
    at finish (/js/javascript-tutorial-server/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/js/javascript-tutorial-server/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/js/javascript-tutorial-server/node_modules/orchestrator/index.js:264:8)
    at /js/javascript-tutorial-server/node_modules/orchestrator/index.js:275:23
    at finish (/js/javascript-tutorial-server/node_modules/orchestrator/lib/runTask.js:21:8)
    at /js/javascript-tutorial-server/node_modules/orchestrator/lib/runTask.js:45:4
    at process._tickCallback (internal/process/next_tick.js:109:7)
Gulp error details [ 'Task ll:client:webpack failed' ]
Gulp error details [ 'Task ll:client:webpack failed' ]

**Comment by mihirchronicles** [comment]
What was the solution for this? I am getting the same error.
